"""Added checkout_request_id column

Revision ID: 0393ee5852b8
Revises: 8afd1d76c659
Create Date: 2026-05-29 06:28:09.460077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0393ee5852b8'
down_revision = '8afd1d76c659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_checkout_request_id', ['checkout_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
