"""fix pricing fields with server defaults

Revision ID: 785785d205bc
Revises: ddf136c3e937
Create Date: 2026-04-07 02:52:19.124477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785785d205bc'
down_revision = 'ddf136c3e937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_price', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('min_stock_level', sa.Integer(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('min_stock_level')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('buying_price')

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=50), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('buying_price', sa.FLOAT(), nullable=False),
    sa.Column('selling_price', sa.FLOAT(), nullable=False),
    sa.Column('min_stock_level', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
