"""Added cash and change to receipt model

Revision ID: 8afd1d76c659
Revises: 785785d205bc
Create Date: 2026-04-16 04:05:41.330045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afd1d76c659'
down_revision = '785785d205bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_received', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('change_given', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('change_given')
        batch_op.drop_column('cash_received')

    # ### end Alembic commands ###
