"""supplier invoice payables tracking

Revision ID: 8dc619c61b7b
Revises: 9559eb77ab28
Create Date: 2026-06-05 15:11:08.094630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc619c61b7b'
down_revision = '9559eb77ab28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
