"""add tax amount column to sale

Revision ID: 9559eb77ab28
Revises: 0393ee5852b8
Create Date: 2026-06-01 22:06:52.474377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9559eb77ab28'
down_revision = '0393ee5852b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('tax_amount')

    # ### end Alembic commands ###
