"""loyalty credit accounts

Revision ID: 9d6d64da913f
Revises: c79991e472fe
Create Date: 2026-06-11 10:27:10.303191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6d64da913f'
down_revision = 'c79991e472fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_item', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('line_total')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('purchase_order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_total', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('unit_cost', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
